language: python
python:
- '3.4'
- '3.5'
- '3.6'

install:
- pip install -e .[test,doc]

script:
- pytest --cov=gaia --cov-report=term-missing
- codecov

notifications:
  slack:
    secure: BE3yzqw8lwUpKAHrYuje6IcYtaEW9se4jbFfG0MWq8mXCiZXzFvGRk2UjApcKG6pC7L5SoXcRJRoPYmNXgoywudVtSgZs3j9yYXiGazJG9sdnFfcHFPKXt2W745GMDecFMn7OKEP4+m3g1VZal4HZtK41iH4Z1w6m3sOuMcY6q5UorlSXenPA/MSCvZ/KFsEqczeFEMiJanjZVv6+lK53pSFuC7pZd32LI5PDUnMgtq2uOZdygE9Ck1r9/nyAXtSBGqIW58kwoVfkBvMIDIXSV0Utqp3u320ERtYh/UrSyuE1sDXrvUEvSCGeE7pn/NZXMYoRCHSo7mG5hh6mObBhuopfs+GTStY/VlBQXKwD/NGgZH1IWcsJpxvDs4MjI5znJVXIi9BK0VKR9Xg3BU+kPLAd2BlrQDzTSF8W/sxSixAOekswt11PdrhOMV9xmhVPtPzXbZCFQ81oOqPTDfUwT/8Qf+Pc0rVM1wQ/aGnH0lGeTRGjZy8ICnzycFqRGhu6zU4xEeABWbW9ZbamtF1YTdKbkBV6mPgfcwgzhB6XvC0JvPyZIJBE8tY2Z494y4zwj81uCTUY5Kh0Wd3FRdu5/PJDMfo9miWh+Ndqn9N4gvU+5EioJZ1M/os+U5CMrLyxukhhmrByZtG+JQVuoN6Mnk4/rgJbJfcVVhrvWipWhk=