language: python
python:
- '3.5'
- '3.6'
- '3.7'
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
- pip install -e .[test,doc]

script:
- pytest --cov=gaia --cov-report=term-missing
- codecov
